# Generated by Django 3.2.9 on 2021-12-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211126_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
