# Generated by Django 3.2.9 on 2022-01-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('requirements', 'Requirements'), ('workspace', 'Workspace'), ('finals', 'Finals'), ('shooting', 'Shooting'), ('info', 'Info')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='departments',
            field=models.CharField(choices=[('camera', 'Camera'), ('script', 'Script'), ('art', 'Art'), ('make-up', 'Hair/Make-up'), ('wardrobe', 'Wardrobe'), ('location', 'Location'), ('sound', 'Sound'), ('casting', 'Casting'), ('post', 'Post/VSF'), ('production', 'Production'), ('stunts', 'Stunts'), ('electric', 'Electric/Grip'), ('universal', 'Universal')], default='universal', max_length=32),
        ),
    ]
