# Generated by Django 3.2.9 on 2022-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('pickup_address', models.TextField(blank=True)),
                ('pickup_address_2', models.TextField(blank=True)),
                ('make_up_time', models.CharField(blank=True, max_length=255)),
                ('commute_time', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255)),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('diet', models.CharField(blank=True, max_length=255)),
                ('requirements', models.CharField(blank=True, max_length=255)),
                ('costume1', models.TextField(blank=True)),
                ('costume1_image', models.ImageField(blank=True, upload_to='images/')),
                ('costume2', models.TextField(blank=True)),
                ('costume2_image', models.ImageField(blank=True, upload_to='images/')),
                ('costume3', models.TextField(blank=True)),
                ('costume3_image', models.ImageField(blank=True, upload_to='images/')),
                ('costume4', models.TextField(blank=True)),
                ('costume4_image', models.ImageField(blank=True, upload_to='images/')),
                ('costume5', models.TextField(blank=True)),
                ('costume5_image', models.ImageField(blank=True, upload_to='images/')),
                ('costume6', models.TextField(blank=True)),
                ('costume6_image', models.ImageField(blank=True, upload_to='images/')),
                ('costume7', models.TextField(blank=True)),
                ('costume7_image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
