# Generated by Django 3.2.9 on 2022-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='costume8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='costume8_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
