# Generated by Django 3.2.9 on 2022-01-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20220103_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='costume8',
        ),
        migrations.RemoveField(
            model_name='character',
            name='costume8_image',
        ),
        migrations.AddField(
            model_name='character',
            name='makeup',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='makeup_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
