# Generated by Django 3.2.9 on 2022-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20220118_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
