# Generated by Django 3.2.9 on 2022-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
