# Generated by Django 3.2.9 on 2022-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
