# Generated by Django 3.2.9 on 2022-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='number',
            field=models.IntegerField(),
        ),
    ]
