# Generated by Django 3.2.9 on 2022-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255)),
                ('story', models.TextField(blank=True)),
                ('style', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
