# Generated by Django 3.2.9 on 2022-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcard',
            name='number',
            field=models.IntegerField(),
        ),
    ]
