""" CrewInfo Model """
from django.db import models
# from scenes.models import Scene


class CrewInfo(models.Model):
    """
    CrewInfo Model
    """

    production_name = models.CharField(max_length=255, blank=True)
    production_company = models.CharField(max_length=255, blank=True)
    company_phone = models.CharField(max_length=255, blank=True)
    company_email = models.CharField(max_length=255, blank=True)
    company_address = models.TextField(blank=True)
    company_logo = models.ImageField(
        upload_to='images/', blank=True
    )
    producer_name = models.CharField(max_length=255, blank=True)
    producer_email = models.CharField(max_length=255, blank=True)
    producer_phone = models.CharField(max_length=255, blank=True)
    pro_coordinator_name = models.CharField(max_length=255, blank=True)
    pro_coordinator_email = models.CharField(max_length=255, blank=True)
    pro_coordinator_phone = models.CharField(max_length=255, blank=True)
    travel_coordinator_name = models.CharField(max_length=255, blank=True)
    travel_coordinator_email = models.CharField(max_length=255, blank=True)
    travel_coordinator_phone = models.CharField(max_length=255, blank=True)
    production_pa_name = models.CharField(max_length=255, blank=True)
    production_pa_phone = models.CharField(max_length=255, blank=True)
    locations_manager_name = models.CharField(max_length=255, blank=True)
    locations_manager_email = models.CharField(max_length=255, blank=True)
    locations_manager_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_phone = models.CharField(max_length=255, blank=True)
    ad_1_name = models.CharField(max_length=255, blank=True)
    ad_1_email = models.CharField(max_length=255, blank=True)
    ad_1_phone = models.CharField(max_length=255, blank=True)
    ad_2_name = models.CharField(max_length=255, blank=True)
    ad_2_email = models.CharField(max_length=255, blank=True)
    ad_2_phone = models.CharField(max_length=255, blank=True)
    ad_3_name = models.CharField(max_length=255, blank=True)
    ad_3_email = models.CharField(max_length=255, blank=True)
    ad_3_phone = models.CharField(max_length=255, blank=True)
    ad_4_name = models.CharField(max_length=255, blank=True)
    ad_4_email = models.CharField(max_length=255, blank=True)
    ad_4_phone = models.CharField(max_length=255, blank=True)
    ad_5_name = models.CharField(max_length=255, blank=True)
    ad_5_email = models.CharField(max_length=255, blank=True)
    ad_5_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_1_name = models.CharField(max_length=255, blank=True)
    pro_assistant_1_email = models.CharField(max_length=255, blank=True)
    pro_assistant_1_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_2_name = models.CharField(max_length=255, blank=True)
    pro_assistant_2_email = models.CharField(max_length=255, blank=True)
    pro_assistant_2_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_3_name = models.CharField(max_length=255, blank=True)
    pro_assistant_3_email = models.CharField(max_length=255, blank=True)
    pro_assistant_3_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_4_name = models.CharField(max_length=255, blank=True)
    pro_assistant_4_email = models.CharField(max_length=255, blank=True)
    pro_assistant_4_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_5_name = models.CharField(max_length=255, blank=True)
    pro_assistant_5_email = models.CharField(max_length=255, blank=True)
    pro_assistant_5_phone = models.CharField(max_length=255, blank=True)
    dop_name = models.CharField(max_length=255, blank=True)
    dop_email = models.CharField(max_length=255, blank=True)
    dop_phone = models.CharField(max_length=255, blank=True)
    camera_operator_name = models.CharField(max_length=255, blank=True)
    camera_operator_email = models.CharField(max_length=255, blank=True)
    camera_operator_phone = models.CharField(max_length=255, blank=True)
    camera_ass_1_name = models.CharField(max_length=255, blank=True)
    camera_ass_1_email = models.CharField(max_length=255, blank=True)
    camera_ass_1_phone = models.CharField(max_length=255, blank=True)
    camera_ass_2_name = models.CharField(max_length=255, blank=True)
    camera_ass_2_email = models.CharField(max_length=255, blank=True)
    camera_ass_2_phone = models.CharField(max_length=255, blank=True)
    dit_name = models.CharField(max_length=255, blank=True)
    dit_email = models.CharField(max_length=255, blank=True)
    dit_phone = models.CharField(max_length=255, blank=True)
    steadicam_name = models.CharField(max_length=255, blank=True)
    steadicam_email = models.CharField(max_length=255, blank=True)
    steadicam_phone = models.CharField(max_length=255, blank=True)
    camera_pa_name = models.CharField(max_length=255, blank=True)
    camera_pa_email = models.CharField(max_length=255, blank=True)
    camera_pa_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_phone = models.CharField(max_length=255, blank=True)
    key_hairmakeup_name = models.CharField(max_length=255, blank=True)
    key_hairmakeup_email = models.CharField(max_length=255, blank=True)
    key_hairmakeup_phone = models.CharField(max_length=255, blank=True)
    key_hairstylist_name = models.CharField(max_length=255, blank=True)
    key_hairstylist_email = models.CharField(max_length=255, blank=True)
    key_hairstylist_phone = models.CharField(max_length=255, blank=True)
    sfx_makeup_name = models.CharField(max_length=255, blank=True)
    sfx_makeup_email = models.CharField(max_length=255, blank=True)
    sfx_makeup_phone = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_name = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_email = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_1_name = models.CharField(max_length=255, blank=True)
    makeup_artist_1_email = models.CharField(max_length=255, blank=True)
    makeup_artist_1_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_2_name = models.CharField(max_length=255, blank=True)
    makeup_artist_2_email = models.CharField(max_length=255, blank=True)
    makeup_artist_2_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_3_name = models.CharField(max_length=255, blank=True)
    makeup_artist_3_email = models.CharField(max_length=255, blank=True)
    makeup_artist_3_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_4_name = models.CharField(max_length=255, blank=True)
    makeup_artist_4_email = models.CharField(max_length=255, blank=True)
    makeup_artist_4_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_5_name = models.CharField(max_length=255, blank=True)
    makeup_artist_5_email = models.CharField(max_length=255, blank=True)
    makeup_artist_5_phone = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['production_name']

    def __str__(self):
        return f'{self.production_name}'
