""" Callsheet Models """
from django.db import models
from schedule.models import Day


class CrewInfo(models.Model):
    """
    CrewInfo Model
    """

    total_shoot_days = models.CharField(max_length=255, blank=True)
    production_name = models.CharField(max_length=255, blank=True)
    production_company = models.CharField(max_length=255, blank=True)
    company_phone = models.CharField(max_length=255, blank=True)
    company_email = models.CharField(max_length=255, blank=True)
    company_address = models.TextField(blank=True)
    company_logo = models.ImageField(
        upload_to='images/', blank=True
    )
    producer_name = models.CharField(max_length=255, blank=True)
    producer_email = models.CharField(max_length=255, blank=True)
    producer_phone = models.CharField(max_length=255, blank=True)
    pro_coordinator_name = models.CharField(max_length=255, blank=True)
    pro_coordinator_email = models.CharField(max_length=255, blank=True)
    pro_coordinator_phone = models.CharField(max_length=255, blank=True)
    travel_coordinator_name = models.CharField(max_length=255, blank=True)
    travel_coordinator_email = models.CharField(max_length=255, blank=True)
    travel_coordinator_phone = models.CharField(max_length=255, blank=True)
    production_pa_name = models.CharField(max_length=255, blank=True)
    production_pa_phone = models.CharField(max_length=255, blank=True)
    locations_manager_name = models.CharField(max_length=255, blank=True)
    locations_manager_email = models.CharField(max_length=255, blank=True)
    locations_manager_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_phone = models.CharField(max_length=255, blank=True)
    ad_1_name = models.CharField(max_length=255, blank=True)
    ad_1_email = models.CharField(max_length=255, blank=True)
    ad_1_phone = models.CharField(max_length=255, blank=True)
    ad_2_name = models.CharField(max_length=255, blank=True)
    ad_2_email = models.CharField(max_length=255, blank=True)
    ad_2_phone = models.CharField(max_length=255, blank=True)
    ad_3_name = models.CharField(max_length=255, blank=True)
    ad_3_email = models.CharField(max_length=255, blank=True)
    ad_3_phone = models.CharField(max_length=255, blank=True)
    ad_4_name = models.CharField(max_length=255, blank=True)
    ad_4_email = models.CharField(max_length=255, blank=True)
    ad_4_phone = models.CharField(max_length=255, blank=True)
    ad_5_name = models.CharField(max_length=255, blank=True)
    ad_5_email = models.CharField(max_length=255, blank=True)
    ad_5_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_1_name = models.CharField(max_length=255, blank=True)
    pro_assistant_1_email = models.CharField(max_length=255, blank=True)
    pro_assistant_1_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_2_name = models.CharField(max_length=255, blank=True)
    pro_assistant_2_email = models.CharField(max_length=255, blank=True)
    pro_assistant_2_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_3_name = models.CharField(max_length=255, blank=True)
    pro_assistant_3_email = models.CharField(max_length=255, blank=True)
    pro_assistant_3_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_4_name = models.CharField(max_length=255, blank=True)
    pro_assistant_4_email = models.CharField(max_length=255, blank=True)
    pro_assistant_4_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_5_name = models.CharField(max_length=255, blank=True)
    pro_assistant_5_email = models.CharField(max_length=255, blank=True)
    pro_assistant_5_phone = models.CharField(max_length=255, blank=True)
    dop_name = models.CharField(max_length=255, blank=True)
    dop_email = models.CharField(max_length=255, blank=True)
    dop_phone = models.CharField(max_length=255, blank=True)
    camera_operator_name = models.CharField(max_length=255, blank=True)
    camera_operator_email = models.CharField(max_length=255, blank=True)
    camera_operator_phone = models.CharField(max_length=255, blank=True)
    camera_ass_1_name = models.CharField(max_length=255, blank=True)
    camera_ass_1_email = models.CharField(max_length=255, blank=True)
    camera_ass_1_phone = models.CharField(max_length=255, blank=True)
    camera_ass_2_name = models.CharField(max_length=255, blank=True)
    camera_ass_2_email = models.CharField(max_length=255, blank=True)
    camera_ass_2_phone = models.CharField(max_length=255, blank=True)
    dit_name = models.CharField(max_length=255, blank=True)
    dit_email = models.CharField(max_length=255, blank=True)
    dit_phone = models.CharField(max_length=255, blank=True)
    steadicam_name = models.CharField(max_length=255, blank=True)
    steadicam_email = models.CharField(max_length=255, blank=True)
    steadicam_phone = models.CharField(max_length=255, blank=True)
    camera_pa_name = models.CharField(max_length=255, blank=True)
    camera_pa_email = models.CharField(max_length=255, blank=True)
    camera_pa_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_phone = models.CharField(max_length=255, blank=True)
    key_hairmakeup_name = models.CharField(max_length=255, blank=True)
    key_hairmakeup_email = models.CharField(max_length=255, blank=True)
    key_hairmakeup_phone = models.CharField(max_length=255, blank=True)
    key_hairstylist_name = models.CharField(max_length=255, blank=True)
    key_hairstylist_email = models.CharField(max_length=255, blank=True)
    key_hairstylist_phone = models.CharField(max_length=255, blank=True)
    sfx_makeup_name = models.CharField(max_length=255, blank=True)
    sfx_makeup_email = models.CharField(max_length=255, blank=True)
    sfx_makeup_phone = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_name = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_email = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_1_name = models.CharField(max_length=255, blank=True)
    makeup_artist_1_email = models.CharField(max_length=255, blank=True)
    makeup_artist_1_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_2_name = models.CharField(max_length=255, blank=True)
    makeup_artist_2_email = models.CharField(max_length=255, blank=True)
    makeup_artist_2_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_3_name = models.CharField(max_length=255, blank=True)
    makeup_artist_3_email = models.CharField(max_length=255, blank=True)
    makeup_artist_3_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_4_name = models.CharField(max_length=255, blank=True)
    makeup_artist_4_email = models.CharField(max_length=255, blank=True)
    makeup_artist_4_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_5_name = models.CharField(max_length=255, blank=True)
    makeup_artist_5_email = models.CharField(max_length=255, blank=True)
    makeup_artist_5_phone = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    sound_mixer_name = models.CharField(max_length=255, blank=True)
    sound_mixer_email = models.CharField(max_length=255, blank=True)
    sound_mixer_phone = models.CharField(max_length=255, blank=True)
    boom_operator_name = models.CharField(max_length=255, blank=True)
    boom_operator_email = models.CharField(max_length=255, blank=True)
    boom_operator_phone = models.CharField(max_length=255, blank=True)
    sound_assistant_1_name = models.CharField(max_length=255, blank=True)
    sound_assistant_1_email = models.CharField(max_length=255, blank=True)
    sound_assistant_1_phone = models.CharField(max_length=255, blank=True)
    sound_assistant_2_name = models.CharField(max_length=255, blank=True)
    sound_assistant_2_email = models.CharField(max_length=255, blank=True)
    sound_assistant_2_phone = models.CharField(max_length=255, blank=True)
    script_supervisor_name = models.CharField(max_length=255, blank=True)
    script_supervisor_email = models.CharField(max_length=255, blank=True)
    script_supervisor_phone = models.CharField(max_length=255, blank=True)
    costume_designer_name = models.CharField(max_length=255, blank=True)
    costume_designer_email = models.CharField(max_length=255, blank=True)
    costume_designer_phone = models.CharField(max_length=255, blank=True)
    ass_costume_designer_name = models.CharField(max_length=255, blank=True)
    ass_costume_designer_email = models.CharField(max_length=255, blank=True)
    ass_costume_designer_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_1_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_1_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_1_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_2_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_2_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_2_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_3_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_3_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_3_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_4_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_4_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_4_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_5_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_5_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_5_phone = models.CharField(max_length=255, blank=True)
    production_designer_name = models.CharField(max_length=255, blank=True)
    production_designer_email = models.CharField(max_length=255, blank=True)
    production_designer_phone = models.CharField(max_length=255, blank=True)
    art_director_name = models.CharField(max_length=255, blank=True)
    art_director_email = models.CharField(max_length=255, blank=True)
    art_director_phone = models.CharField(max_length=255, blank=True)
    art_assistant_name = models.CharField(max_length=255, blank=True)
    art_assistant_email = models.CharField(max_length=255, blank=True)
    art_assistant_phone = models.CharField(max_length=255, blank=True)
    set_decorator_name = models.CharField(max_length=255, blank=True)
    set_decorator_email = models.CharField(max_length=255, blank=True)
    set_decorator_phone = models.CharField(max_length=255, blank=True)
    set_dresser_name = models.CharField(max_length=255, blank=True)
    set_dresser_email = models.CharField(max_length=255, blank=True)
    set_dresser_phone = models.CharField(max_length=255, blank=True)
    lead_man_name = models.CharField(max_length=255, blank=True)
    lead_man_email = models.CharField(max_length=255, blank=True)
    lead_man_phone = models.CharField(max_length=255, blank=True)
    dresser_name = models.CharField(max_length=255, blank=True)
    dresser_email = models.CharField(max_length=255, blank=True)
    dresser_phone = models.CharField(max_length=255, blank=True)
    prop_master_name = models.CharField(max_length=255, blank=True)
    prop_master_email = models.CharField(max_length=255, blank=True)
    prop_master_phone = models.CharField(max_length=255, blank=True)
    ass_prop_master_name = models.CharField(max_length=255, blank=True)
    ass_prop_master_email = models.CharField(max_length=255, blank=True)
    ass_prop_master_phone = models.CharField(max_length=255, blank=True)
    prop_buyer_name = models.CharField(max_length=255, blank=True)
    prop_buyer_email = models.CharField(max_length=255, blank=True)
    prop_buyer_phone = models.CharField(max_length=255, blank=True)
    armorer_name = models.CharField(max_length=255, blank=True)
    armorer_email = models.CharField(max_length=255, blank=True)
    armorer_phone = models.CharField(max_length=255, blank=True)
    gaffer_name = models.CharField(max_length=255, blank=True)
    gaffer_email = models.CharField(max_length=255, blank=True)
    gaffer_phone = models.CharField(max_length=255, blank=True)
    best_boy_electric_name = models.CharField(max_length=255, blank=True)
    best_boy_electric_email = models.CharField(max_length=255, blank=True)
    best_boy_electric_phone = models.CharField(max_length=255, blank=True)
    electric_3_name = models.CharField(max_length=255, blank=True)
    electric_3_email = models.CharField(max_length=255, blank=True)
    electric_3_phone = models.CharField(max_length=255, blank=True)
    electric_4_name = models.CharField(max_length=255, blank=True)
    electric_4_email = models.CharField(max_length=255, blank=True)
    electric_4_phone = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)
    # production_name = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['production_name']

    def __str__(self):
        return f'{self.production_name}'


class Callsheet(models.Model):
    """
    Callsheet Model
    """

    day_id = models.ForeignKey(Day, on_delete=models.CASCADE)
    day = models.TextField(blank=True)
    date = models.TextField(blank=True, default="")
    unit_call = models.CharField(max_length=255, blank=True)
    talent_call = models.CharField(max_length=255, blank=True)
    shoot_call = models.CharField(max_length=255, blank=True)
    breakfast = models.CharField(max_length=255, blank=True)
    lunch = models.CharField(max_length=255, blank=True)
    wrap = models.CharField(max_length=255, blank=True)
    basecamp_address = models.TextField(blank=True)
    basecamp_parking_n_notes = models.TextField(blank=True)
    location_1_address = models.TextField(blank=True)
    location_2_address = models.TextField(blank=True)
    location_3_address = models.TextField(blank=True)
    location_4_address = models.TextField(blank=True)
    location_5_address = models.TextField(blank=True)
    location_1_parking_n_notes = models.TextField(blank=True)
    location_2_parking_n_notes = models.TextField(blank=True)
    location_3_parking_n_notes = models.TextField(blank=True)
    location_4_parking_n_notes = models.TextField(blank=True)
    location_5_parking_n_notes = models.TextField(blank=True)
    nearest_hospital = models.TextField(blank=True)
    weather_location = models.CharField(max_length=255, blank=True)
    important_info = models.TextField(blank=True)
    transport_info = models.TextField(blank=True)
    department_info = models.TextField(blank=True)

    class Meta:
        ordering = ['day']

    def __str__(self):
        return f'{self.day}'


class Castcall(models.Model):
    """
    Castcall Model
    """

    day_id = models.ForeignKey(Day, on_delete=models.CASCADE)
    day = models.CharField(max_length=255, blank=True)
    date = models.CharField(max_length=255, blank=True)
    cast_number = models.CharField(max_length=255, blank=True)
    role = models.CharField(max_length=255, blank=True)
    artist = models.CharField(max_length=255, blank=True)
    contact = models.CharField(max_length=255, blank=True)
    swf = models.CharField(max_length=255, blank=True)
    pickup = models.CharField(max_length=255, blank=True)
    call = models.TextField(blank=True)
    hmw = models.TextField(blank=True)
    on_set = models.TextField(blank=True)
    inst = models.TextField(blank=True)

    class Meta:
        ordering = ['cast_number']

    def __str__(self):
        return f'{self.role}'


class Backgroundcall(models.Model):
    """
    Backgroundcall Model
    """

    day_id = models.ForeignKey(Day, on_delete=models.CASCADE)
    day = models.CharField(max_length=255, blank=True)
    date = models.CharField(max_length=255, blank=True)
    qty = models.CharField(max_length=255, blank=True)
    type = models.CharField(max_length=255, blank=True)
    call = models.CharField(max_length=255, blank=True)
    scenes = models.CharField(max_length=255, blank=True)
    set = models.CharField(max_length=255, blank=True)
    costumes = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['call']

    def __str__(self):
        return f'{self.type}'
