# Generated by Django 3.2.9 on 2021-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('int_ext', models.CharField(choices=[('ext', 'EXT.'), ('int', 'INT.')], default='int', max_length=32)),
                ('time', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('characters', models.CharField(blank=True, max_length=255)),
                ('info', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
