# Generated by Django 3.2.9 on 2021-11-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='characters',
        ),
        migrations.AddField(
            model_name='scene',
            name='shotlist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='storyboard',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
