# Generated by Django 3.2.9 on 2021-11-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_scene_chatacters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='chatacters',
            new_name='characters',
        ),
    ]
