# Generated by Django 3.2.9 on 2021-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0004_rename_chatacters_scene_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='act',
            field=models.CharField(choices=[('one', 'One'), ('two-a', 'Two - First Half'), ('two-b', 'Two - Second Half'), ('three', 'Three')], default='one', max_length=32),
        ),
        migrations.AddField(
            model_name='scene',
            name='day_night',
            field=models.CharField(choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='day', max_length=32),
        ),
    ]
