# Generated by Django 3.2.9 on 2021-12-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0005_auto_20211219_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='day_night',
            field=models.CharField(blank=True, choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='day', max_length=32),
        ),
        migrations.AlterField(
            model_name='scene',
            name='int_ext',
            field=models.CharField(blank=True, choices=[('ext', 'EXT.'), ('int', 'INT.')], default='int', max_length=32),
        ),
        migrations.AlterField(
            model_name='scene',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scene',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
