# Generated by Django 3.2.9 on 2022-01-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0009_auto_20211230_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='pages',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
