# Generated by Django 3.2.9 on 2022-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0011_auto_20220113_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='shooting_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
