# Generated by Django 3.2.9 on 2022-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0012_alter_scene_shooting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='content',
            new_name='department_info',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='info',
        ),
        migrations.AddField(
            model_name='scene',
            name='dramatic_day',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scene',
            name='equip_set_props',
            field=models.TextField(blank=True),
        ),
    ]
