# Generated by Django 3.2.9 on 2022-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0013_auto_20220313_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='character10_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character11_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character12_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character1_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character2_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character3_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character4_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character5_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character6_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character7_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character8_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='character9_number',
            field=models.TextField(blank=True),
        ),
    ]
