# Generated by Django 3.2.9 on 2022-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0014_auto_20220526_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='images/'),
        ),
    ]
