# Generated by Django 3.2.9 on 2022-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0015_alter_scene_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
