# Generated by Django 3.2.9 on 2022-07-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0017_alter_scene_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='image',
            new_name='script',
        ),
    ]
