# Generated by Django 3.2.9 on 2022-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0018_rename_image_scene_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='location_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
