# Generated by Django 3.2.9 on 2022-11-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0020_scenecharacteradd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneBGAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('costume', models.CharField(blank=True, max_length=255)),
                ('scene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.scene')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
