# Generated by Django 3.2.9 on 2024-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0023_auto_20240825_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='day_night',
            field=models.CharField(blank=True, choices=[('DAY', 'DAY'), ('NIGHT', 'NIGHT')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scene',
            name='int_ext',
            field=models.CharField(blank=True, choices=[('ext', 'EXT.'), ('int', 'INT.')], max_length=32),
        ),
    ]
