# Generated by Django 3.2.9 on 2024-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0024_auto_20241124_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='int_ext',
            field=models.CharField(blank=True, choices=[('ext', 'EXT'), ('int', 'INT')], max_length=32),
        ),
    ]
