# Generated by Django 3.2.9 on 2024-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0025_alter_scene_int_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='int_ext',
            field=models.CharField(blank=True, choices=[('ext.', 'EXT'), ('int.', 'INT')], max_length=32),
        ),
    ]
