# Generated by Django 3.2.9 on 2021-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('scene', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
