# Generated by Django 3.2.9 on 2021-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20211225_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='location6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='day',
            name='scene11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='day',
            name='scene12',
            field=models.TextField(blank=True),
        ),
    ]
