# Generated by Django 3.2.9 on 2021-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20211229_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescene',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
