# Generated by Django 3.2.9 on 2021-12-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedulescene_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulescene',
            name='new_content',
            field=models.TextField(blank=True),
        ),
    ]
