# Generated by Django 3.2.9 on 2021-12-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20211230_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescene',
            name='date',
            field=models.TextField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
