# Generated by Django 3.2.9 on 2021-12-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_schedulescene_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescene',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
