# Generated by Django 3.2.9 on 2022-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20220105_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulescene',
            name='pages',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
