# Generated by Django 3.2.9 on 2022-01-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_schedulescene_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescene',
            name='character10_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character10_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character11_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character11_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character12_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character12_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character1_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character1_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character2_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character2_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character3_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character3_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character4_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character4_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character5_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character5_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character6_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character6_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character7_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character7_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character8_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character8_pickup',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character9_calltime',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='character9_pickup',
            field=models.TextField(blank=True, default=''),
        ),
    ]
