# Generated by Django 3.2.9 on 2022-02-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20220105_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='day',
            name='location3',
        ),
        migrations.RemoveField(
            model_name='day',
            name='location4',
        ),
        migrations.RemoveField(
            model_name='day',
            name='location5',
        ),
        migrations.RemoveField(
            model_name='day',
            name='location6',
        ),
        migrations.AddField(
            model_name='day',
            name='xtra_scenes',
            field=models.TextField(blank=True),
        ),
    ]
