# Generated by Django 3.2.9 on 2022-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20220312_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulescene',
            old_name='content',
            new_name='department_info',
        ),
        migrations.RemoveField(
            model_name='schedulescene',
            name='info',
        ),
        migrations.RemoveField(
            model_name='schedulescene',
            name='new_content',
        ),
        migrations.AddField(
            model_name='schedulescene',
            name='dramatic_day',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedulescene',
            name='equip_set_props',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedulescene',
            name='location_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schedulescene',
            name='next',
            field=models.TextField(blank=True),
        ),
    ]
