# Generated by Django 3.2.9 on 2022-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20220313_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescene',
            name='day_order_number',
            field=models.IntegerField(blank=True),
        ),
    ]
