# Generated by Django 3.2.9 on 2024-08-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20221204_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default='1 Jan 23'),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedulescene',
            name='day_order_number',
            field=models.IntegerField(),
        ),
    ]
