# Generated by Django 3.2.9 on 2024-08-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20240810_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default='2024-11-11'),
        ),
    ]
