# Generated by Django 3.2.9 on 2022-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexshots1', '0002_auto_20220608_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexshot',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
