# Generated by Django 3.2.9 on 2022-03-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20220227_0026'),
        ('callsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewinfo',
            name='total_shoot_days',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Callsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(blank=True)),
                ('date', models.TextField(blank=True, default='')),
                ('unit_call', models.CharField(blank=True, max_length=255)),
                ('talent_call', models.CharField(blank=True, max_length=255)),
                ('shoot_call', models.CharField(blank=True, max_length=255)),
                ('breakfast', models.CharField(blank=True, max_length=255)),
                ('lunch', models.CharField(blank=True, max_length=255)),
                ('wrap', models.CharField(blank=True, max_length=255)),
                ('basecamp_address', models.TextField(blank=True)),
                ('basecamp_parking_n_notes', models.TextField(blank=True)),
                ('location_1_address', models.TextField(blank=True)),
                ('location_2_address', models.TextField(blank=True)),
                ('location_3_address', models.TextField(blank=True)),
                ('location_4_address', models.TextField(blank=True)),
                ('location_5_address', models.TextField(blank=True)),
                ('location_1_parking_n_notes', models.TextField(blank=True)),
                ('location_2_parking_n_notes', models.TextField(blank=True)),
                ('location_3_parking_n_notes', models.TextField(blank=True)),
                ('location_4_parking_n_notes', models.TextField(blank=True)),
                ('location_5_parking_n_notes', models.TextField(blank=True)),
                ('nearest_hospital', models.TextField(blank=True)),
                ('weather_para', models.CharField(blank=True, max_length=255)),
                ('important_info', models.TextField(blank=True)),
                ('transport_info', models.TextField(blank=True)),
                ('department_info', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=255)),
                ('company_email', models.CharField(blank=True, max_length=255)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
