# Generated by Django 3.2.9 on 2022-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0002_auto_20220308_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='weather_para',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='weather_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='armorer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='armorer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='armorer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='art_assistant_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='art_assistant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='art_assistant_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='art_director_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='art_director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='art_director_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='ass_costume_designer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='ass_costume_designer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='ass_costume_designer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='ass_prop_master_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='ass_prop_master_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='ass_prop_master_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='best_boy_electric_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='best_boy_electric_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='best_boy_electric_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='boom_operator_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='boom_operator_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='boom_operator_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='costume_designer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='costume_designer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='costume_designer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='dresser_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='dresser_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='dresser_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='electric_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='electric_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='electric_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='electric_4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='electric_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='electric_4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='gaffer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='gaffer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='gaffer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='lead_man_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='lead_man_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='lead_man_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='production_designer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='production_designer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='production_designer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='prop_buyer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='prop_buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='prop_buyer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='prop_master_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='prop_master_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='prop_master_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='script_supervisor_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='script_supervisor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='script_supervisor_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_decorator_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_decorator_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_decorator_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_dresser_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_dresser_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_dresser_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_assistant_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_assistant_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_assistant_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_assistant_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_assistant_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_assistant_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_mixer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_mixer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='sound_mixer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_5_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='wardrobe_assistant_5_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
