# Generated by Django 3.2.9 on 2022-03-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20220313_2046'),
        ('callsheets', '0005_auto_20220312_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgroundcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=255)),
                ('qty', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('call', models.CharField(blank=True, max_length=255)),
                ('scenes', models.CharField(blank=True, max_length=255)),
                ('set', models.CharField(blank=True, max_length=255)),
                ('costumes', models.CharField(blank=True, max_length=255)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
            ],
            options={
                'ordering': ['call'],
            },
        ),
    ]
