# Generated by Django 3.2.9 on 2022-03-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0006_backgroundcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_art_dept',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_camera',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_electric',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_grip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_open',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_production',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_rollover',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='walkie_channel_transportation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='a0dd_pos_9_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_10_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_10_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_10_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_10_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_1_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_2_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_3_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_4_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_5_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_5_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_5_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_6_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_6_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_6_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_6_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_7_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_7_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_7_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_7_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_8_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_8_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_8_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_8_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_9_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_9_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='add_pos_9_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='all_other_add_positions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='best_boy_grip_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='best_boy_grip_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='best_boy_grip_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='car3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='casting_director_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='casting_director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='casting_director_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='catering_co_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='craft_service_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='craft_service_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='craft_service_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='crafty_ass_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='crafty_ass_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='crafty_ass_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='dolly_grip_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='dolly_grip_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='dolly_grip_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='editor_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='editor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='editor_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='extras_casting_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='extras_casting_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='extras_casting_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='fx_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='fx_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='fx_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='head_driver_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='head_driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='head_driver_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='keygrip_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='keygrip_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='keygrip_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='legal_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='legal_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_ass_4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_mngr_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_mngr_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_mngr_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_security_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_security_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='location_security_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_medic_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_medic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='set_medic_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunt_coordinator_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunt_coordinator_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunt_coordinator_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_5_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='stunts_5_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge5_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='swing_ge5_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_captain_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_captain_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_captain_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_manager_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_manager_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_manager_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_manager_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_manager_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='transport_manager_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='truck3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='writer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='writer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='writer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
