# Generated by Django 3.2.9 on 2022-03-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0007_auto_20220316_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewinfo',
            old_name='company_address',
            new_name='company_address_line_1',
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='company_address_line_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='company_address_line_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crewinfo',
            name='company_address_line_4',
            field=models.TextField(blank=True),
        ),
    ]
