# Generated by Django 3.2.9 on 2022-03-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0008_auto_20220318_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundcall',
            old_name='date',
            new_name='background_shoot_date',
        ),
        migrations.RenameField(
            model_name='backgroundcall',
            old_name='day',
            new_name='background_shoot_day',
        ),
        migrations.RenameField(
            model_name='castcall',
            old_name='date',
            new_name='cast_shoot_date',
        ),
        migrations.RenameField(
            model_name='castcall',
            old_name='day',
            new_name='cast_shoot_day',
        ),
    ]
