# Generated by Django 3.2.9 on 2022-03-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0009_auto_20220318_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundcall',
            name='background_shoot_date',
        ),
        migrations.RemoveField(
            model_name='backgroundcall',
            name='background_shoot_day',
        ),
        migrations.RemoveField(
            model_name='castcall',
            name='cast_shoot_date',
        ),
        migrations.RemoveField(
            model_name='castcall',
            name='cast_shoot_day',
        ),
        migrations.AddField(
            model_name='backgroundcall',
            name='shoot_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='backgroundcall',
            name='shoot_day',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='castcall',
            name='shoot_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='castcall',
            name='shoot_day',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
