""" Callsheetnew Models """
from django.db import models
from schedule.models import Day


class CrewInfonew(models.Model):
    """
    CrewInfonew Model
    """

    total_shoot_days = models.CharField(max_length=255, blank=True)
    production_name = models.CharField(max_length=255, blank=True)
    production_company = models.CharField(max_length=255, blank=True)
    company_phone = models.CharField(max_length=255, blank=True)
    company_email = models.CharField(max_length=255, blank=True)
    company_address_line_1 = models.TextField(blank=True)
    company_address_line_2 = models.TextField(blank=True)
    company_address_line_3 = models.TextField(blank=True)
    company_address_line_4 = models.TextField(blank=True)
    company_logo = models.ImageField(
        upload_to='images/', blank=True
    )
    director_name = models.CharField(max_length=255, blank=True)
    director_email = models.CharField(max_length=255, blank=True)
    director_phone = models.CharField(max_length=255, blank=True)
    producer_name = models.CharField(max_length=255, blank=True)
    producer_email = models.CharField(max_length=255, blank=True)
    producer_phone = models.CharField(max_length=255, blank=True)
    pro_coordinator_name = models.CharField(max_length=255, blank=True)
    pro_coordinator_email = models.CharField(max_length=255, blank=True)
    pro_coordinator_phone = models.CharField(max_length=255, blank=True)
    travel_coordinator_name = models.CharField(max_length=255, blank=True)
    travel_coordinator_email = models.CharField(max_length=255, blank=True)
    travel_coordinator_phone = models.CharField(max_length=255, blank=True)
    production_pa_name = models.CharField(max_length=255, blank=True)
    production_pa_phone = models.CharField(max_length=255, blank=True)
    production_pa_email = models.CharField(max_length=255, blank=True)
    upm_name = models.CharField(max_length=255, blank=True)
    upm_phone = models.CharField(max_length=255, blank=True)
    upm_email = models.CharField(max_length=255, blank=True)
    locations_manager_name = models.CharField(max_length=255, blank=True)
    locations_manager_email = models.CharField(max_length=255, blank=True)
    locations_manager_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_2_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_3_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_4_phone = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_job = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_name = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_email = models.CharField(max_length=255, blank=True)
    oth_production_pos_5_phone = models.CharField(max_length=255, blank=True)
    ad_1_name = models.CharField(max_length=255, blank=True)
    ad_1_email = models.CharField(max_length=255, blank=True)
    ad_1_phone = models.CharField(max_length=255, blank=True)
    ad_2_name = models.CharField(max_length=255, blank=True)
    ad_2_email = models.CharField(max_length=255, blank=True)
    ad_2_phone = models.CharField(max_length=255, blank=True)
    ad_3_name = models.CharField(max_length=255, blank=True)
    ad_3_email = models.CharField(max_length=255, blank=True)
    ad_3_phone = models.CharField(max_length=255, blank=True)
    ad_4_name = models.CharField(max_length=255, blank=True)
    ad_4_email = models.CharField(max_length=255, blank=True)
    ad_4_phone = models.CharField(max_length=255, blank=True)
    ad_5_name = models.CharField(max_length=255, blank=True)
    ad_5_email = models.CharField(max_length=255, blank=True)
    ad_5_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_1_name = models.CharField(max_length=255, blank=True)
    pro_assistant_1_email = models.CharField(max_length=255, blank=True)
    pro_assistant_1_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_2_name = models.CharField(max_length=255, blank=True)
    pro_assistant_2_email = models.CharField(max_length=255, blank=True)
    pro_assistant_2_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_3_name = models.CharField(max_length=255, blank=True)
    pro_assistant_3_email = models.CharField(max_length=255, blank=True)
    pro_assistant_3_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_4_name = models.CharField(max_length=255, blank=True)
    pro_assistant_4_email = models.CharField(max_length=255, blank=True)
    pro_assistant_4_phone = models.CharField(max_length=255, blank=True)
    pro_assistant_5_name = models.CharField(max_length=255, blank=True)
    pro_assistant_5_email = models.CharField(max_length=255, blank=True)
    pro_assistant_5_phone = models.CharField(max_length=255, blank=True)
    dop_name = models.CharField(max_length=255, blank=True)
    dop_email = models.CharField(max_length=255, blank=True)
    dop_phone = models.CharField(max_length=255, blank=True)
    camera_operator_name = models.CharField(max_length=255, blank=True)
    camera_operator_email = models.CharField(max_length=255, blank=True)
    camera_operator_phone = models.CharField(max_length=255, blank=True)
    camera_ass_1_name = models.CharField(max_length=255, blank=True)
    camera_ass_1_email = models.CharField(max_length=255, blank=True)
    camera_ass_1_phone = models.CharField(max_length=255, blank=True)
    camera_ass_2_name = models.CharField(max_length=255, blank=True)
    camera_ass_2_email = models.CharField(max_length=255, blank=True)
    camera_ass_2_phone = models.CharField(max_length=255, blank=True)
    dit_name = models.CharField(max_length=255, blank=True)
    dit_email = models.CharField(max_length=255, blank=True)
    dit_phone = models.CharField(max_length=255, blank=True)
    steadicam_name = models.CharField(max_length=255, blank=True)
    steadicam_email = models.CharField(max_length=255, blank=True)
    steadicam_phone = models.CharField(max_length=255, blank=True)
    camera_pa_name = models.CharField(max_length=255, blank=True)
    camera_pa_email = models.CharField(max_length=255, blank=True)
    camera_pa_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_4_phone = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_job = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_name = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_email = models.CharField(max_length=255, blank=True)
    oth_camera_pos_5_phone = models.CharField(max_length=255, blank=True)
    key_hairmakeup_name = models.CharField(max_length=255, blank=True)
    key_hairmakeup_email = models.CharField(max_length=255, blank=True)
    key_hairmakeup_phone = models.CharField(max_length=255, blank=True)
    key_hairstylist_name = models.CharField(max_length=255, blank=True)
    key_hairstylist_email = models.CharField(max_length=255, blank=True)
    key_hairstylist_phone = models.CharField(max_length=255, blank=True)
    sfx_makeup_name = models.CharField(max_length=255, blank=True)
    sfx_makeup_email = models.CharField(max_length=255, blank=True)
    sfx_makeup_phone = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_name = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_email = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_1_name = models.CharField(max_length=255, blank=True)
    makeup_artist_1_email = models.CharField(max_length=255, blank=True)
    makeup_artist_1_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_2_name = models.CharField(max_length=255, blank=True)
    makeup_artist_2_email = models.CharField(max_length=255, blank=True)
    makeup_artist_2_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_3_name = models.CharField(max_length=255, blank=True)
    makeup_artist_3_email = models.CharField(max_length=255, blank=True)
    makeup_artist_3_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_4_name = models.CharField(max_length=255, blank=True)
    makeup_artist_4_email = models.CharField(max_length=255, blank=True)
    makeup_artist_4_phone = models.CharField(max_length=255, blank=True)
    makeup_artist_5_name = models.CharField(max_length=255, blank=True)
    makeup_artist_5_email = models.CharField(max_length=255, blank=True)
    makeup_artist_5_phone = models.CharField(max_length=255, blank=True)
    sound_mixer_name = models.CharField(max_length=255, blank=True)
    sound_mixer_email = models.CharField(max_length=255, blank=True)
    sound_mixer_phone = models.CharField(max_length=255, blank=True)
    boom_operator_name = models.CharField(max_length=255, blank=True)
    boom_operator_email = models.CharField(max_length=255, blank=True)
    boom_operator_phone = models.CharField(max_length=255, blank=True)
    sound_assistant_1_name = models.CharField(max_length=255, blank=True)
    sound_assistant_1_email = models.CharField(max_length=255, blank=True)
    sound_assistant_1_phone = models.CharField(max_length=255, blank=True)
    sound_assistant_2_name = models.CharField(max_length=255, blank=True)
    sound_assistant_2_email = models.CharField(max_length=255, blank=True)
    sound_assistant_2_phone = models.CharField(max_length=255, blank=True)
    script_supervisor_name = models.CharField(max_length=255, blank=True)
    script_supervisor_email = models.CharField(max_length=255, blank=True)
    script_supervisor_phone = models.CharField(max_length=255, blank=True)
    costume_designer_name = models.CharField(max_length=255, blank=True)
    costume_designer_email = models.CharField(max_length=255, blank=True)
    costume_designer_phone = models.CharField(max_length=255, blank=True)
    ass_costume_designer_name = models.CharField(max_length=255, blank=True)
    ass_costume_designer_email = models.CharField(max_length=255, blank=True)
    ass_costume_designer_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_1_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_1_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_1_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_2_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_2_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_2_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_3_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_3_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_3_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_4_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_4_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_4_phone = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_5_name = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_5_email = models.CharField(max_length=255, blank=True)
    wardrobe_assistant_5_phone = models.CharField(max_length=255, blank=True)
    production_designer_name = models.CharField(max_length=255, blank=True)
    production_designer_email = models.CharField(max_length=255, blank=True)
    production_designer_phone = models.CharField(max_length=255, blank=True)
    art_director_name = models.CharField(max_length=255, blank=True)
    art_director_email = models.CharField(max_length=255, blank=True)
    art_director_phone = models.CharField(max_length=255, blank=True)
    art_assistant_name = models.CharField(max_length=255, blank=True)
    art_assistant_email = models.CharField(max_length=255, blank=True)
    art_assistant_phone = models.CharField(max_length=255, blank=True)
    set_decorator_name = models.CharField(max_length=255, blank=True)
    set_decorator_email = models.CharField(max_length=255, blank=True)
    set_decorator_phone = models.CharField(max_length=255, blank=True)
    set_dresser_name = models.CharField(max_length=255, blank=True)
    set_dresser_email = models.CharField(max_length=255, blank=True)
    set_dresser_phone = models.CharField(max_length=255, blank=True)
    lead_man_name = models.CharField(max_length=255, blank=True)
    lead_man_email = models.CharField(max_length=255, blank=True)
    lead_man_phone = models.CharField(max_length=255, blank=True)
    dresser_name = models.CharField(max_length=255, blank=True)
    dresser_email = models.CharField(max_length=255, blank=True)
    dresser_phone = models.CharField(max_length=255, blank=True)
    prop_master_name = models.CharField(max_length=255, blank=True)
    prop_master_email = models.CharField(max_length=255, blank=True)
    prop_master_phone = models.CharField(max_length=255, blank=True)
    ass_prop_master_name = models.CharField(max_length=255, blank=True)
    ass_prop_master_email = models.CharField(max_length=255, blank=True)
    ass_prop_master_phone = models.CharField(max_length=255, blank=True)
    prop_buyer_name = models.CharField(max_length=255, blank=True)
    prop_buyer_email = models.CharField(max_length=255, blank=True)
    prop_buyer_phone = models.CharField(max_length=255, blank=True)
    armorer_name = models.CharField(max_length=255, blank=True)
    armorer_email = models.CharField(max_length=255, blank=True)
    armorer_phone = models.CharField(max_length=255, blank=True)
    gaffer_name = models.CharField(max_length=255, blank=True)
    gaffer_email = models.CharField(max_length=255, blank=True)
    gaffer_phone = models.CharField(max_length=255, blank=True)
    best_boy_electric_name = models.CharField(max_length=255, blank=True)
    best_boy_electric_email = models.CharField(max_length=255, blank=True)
    best_boy_electric_phone = models.CharField(max_length=255, blank=True)
    electric_3_name = models.CharField(max_length=255, blank=True)
    electric_3_email = models.CharField(max_length=255, blank=True)
    electric_3_phone = models.CharField(max_length=255, blank=True)
    electric_4_name = models.CharField(max_length=255, blank=True)
    electric_4_email = models.CharField(max_length=255, blank=True)
    electric_4_phone = models.CharField(max_length=255, blank=True)
    keygrip_name = models.CharField(max_length=255, blank=True)
    keygrip_email = models.CharField(max_length=255, blank=True)
    keygrip_phone = models.CharField(max_length=255, blank=True)
    best_boy_grip_name = models.CharField(max_length=255, blank=True)
    best_boy_grip_email = models.CharField(max_length=255, blank=True)
    best_boy_grip_phone = models.CharField(max_length=255, blank=True)
    dolly_grip_name = models.CharField(max_length=255, blank=True)
    dolly_grip_email = models.CharField(max_length=255, blank=True)
    dolly_grip_phone = models.CharField(max_length=255, blank=True)
    swing_ge1_name = models.CharField(max_length=255, blank=True)
    swing_ge1_email = models.CharField(max_length=255, blank=True)
    swing_ge1_phone = models.CharField(max_length=255, blank=True)
    swing_ge2_name = models.CharField(max_length=255, blank=True)
    swing_ge2_email = models.CharField(max_length=255, blank=True)
    swing_ge2_phone = models.CharField(max_length=255, blank=True)
    swing_ge3_name = models.CharField(max_length=255, blank=True)
    swing_ge3_email = models.CharField(max_length=255, blank=True)
    swing_ge3_phone = models.CharField(max_length=255, blank=True)
    swing_ge4_name = models.CharField(max_length=255, blank=True)
    swing_ge4_email = models.CharField(max_length=255, blank=True)
    swing_ge4_phone = models.CharField(max_length=255, blank=True)
    swing_ge5_name = models.CharField(max_length=255, blank=True)
    swing_ge5_email = models.CharField(max_length=255, blank=True)
    swing_ge5_phone = models.CharField(max_length=255, blank=True)
    stunt_coordinator_name = models.CharField(max_length=255, blank=True)
    stunt_coordinator_email = models.CharField(max_length=255, blank=True)
    stunt_coordinator_phone = models.CharField(max_length=255, blank=True)
    stunts_1_name = models.CharField(max_length=255, blank=True)
    stunts_1_email = models.CharField(max_length=255, blank=True)
    stunts_1_phone = models.CharField(max_length=255, blank=True)
    stunts_2_name = models.CharField(max_length=255, blank=True)
    stunts_2_email = models.CharField(max_length=255, blank=True)
    stunts_2_phone = models.CharField(max_length=255, blank=True)
    stunts_3_name = models.CharField(max_length=255, blank=True)
    stunts_3_email = models.CharField(max_length=255, blank=True)
    stunts_3_phone = models.CharField(max_length=255, blank=True)
    stunts_4_name = models.CharField(max_length=255, blank=True)
    stunts_4_email = models.CharField(max_length=255, blank=True)
    stunts_4_phone = models.CharField(max_length=255, blank=True)
    stunts_5_name = models.CharField(max_length=255, blank=True)
    stunts_5_email = models.CharField(max_length=255, blank=True)
    stunts_5_phone = models.CharField(max_length=255, blank=True)
    legal_name = models.CharField(max_length=255, blank=True)
    legal_email = models.CharField(max_length=255, blank=True)
    legal_phone = models.CharField(max_length=255, blank=True)
    editor_name = models.CharField(max_length=255, blank=True)
    editor_email = models.CharField(max_length=255, blank=True)
    editor_phone = models.CharField(max_length=255, blank=True)
    writer_name = models.CharField(max_length=255, blank=True)
    writer_email = models.CharField(max_length=255, blank=True)
    writer_phone = models.CharField(max_length=255, blank=True)
    fx_name = models.CharField(max_length=255, blank=True)
    fx_email = models.CharField(max_length=255, blank=True)
    fx_phone = models.CharField(max_length=255, blank=True)
    set_medic_name = models.CharField(max_length=255, blank=True)
    set_medic_email = models.CharField(max_length=255, blank=True)
    set_medic_phone = models.CharField(max_length=255, blank=True)
    casting_director_name = models.CharField(max_length=255, blank=True)
    casting_director_email = models.CharField(max_length=255, blank=True)
    casting_director_phone = models.CharField(max_length=255, blank=True)
    extras_casting_name = models.CharField(max_length=255, blank=True)
    extras_casting_email = models.CharField(max_length=255, blank=True)
    extras_casting_phone = models.CharField(max_length=255, blank=True)
    location_mngr_name = models.CharField(max_length=255, blank=True)
    location_mngr_email = models.CharField(max_length=255, blank=True)
    location_mngr_phone = models.CharField(max_length=255, blank=True)
    location_ass_1_name = models.CharField(max_length=255, blank=True)
    location_ass_1_email = models.CharField(max_length=255, blank=True)
    location_ass_1_phone = models.CharField(max_length=255, blank=True)
    location_ass_2_name = models.CharField(max_length=255, blank=True)
    location_ass_2_email = models.CharField(max_length=255, blank=True)
    location_ass_2_phone = models.CharField(max_length=255, blank=True)
    location_ass_3_name = models.CharField(max_length=255, blank=True)
    location_ass_3_email = models.CharField(max_length=255, blank=True)
    location_ass_3_phone = models.CharField(max_length=255, blank=True)
    location_ass_4_name = models.CharField(max_length=255, blank=True)
    location_ass_4_email = models.CharField(max_length=255, blank=True)
    location_ass_4_phone = models.CharField(max_length=255, blank=True)
    location_security_name = models.CharField(max_length=255, blank=True)
    location_security_email = models.CharField(max_length=255, blank=True)
    location_security_phone = models.CharField(max_length=255, blank=True)
    transport_captain_name = models.CharField(max_length=255, blank=True)
    transport_captain_email = models.CharField(max_length=255, blank=True)
    transport_captain_phone = models.CharField(max_length=255, blank=True)
    transport_manager_1_name = models.CharField(max_length=255, blank=True)
    transport_manager_1_email = models.CharField(max_length=255, blank=True)
    transport_manager_1_phone = models.CharField(max_length=255, blank=True)
    transport_manager_2_name = models.CharField(max_length=255, blank=True)
    transport_manager_2_email = models.CharField(max_length=255, blank=True)
    transport_manager_2_phone = models.CharField(max_length=255, blank=True)
    head_driver_name = models.CharField(max_length=255, blank=True)
    head_driver_email = models.CharField(max_length=255, blank=True)
    head_driver_phone = models.CharField(max_length=255, blank=True)
    truck1_name = models.CharField(max_length=255, blank=True)
    truck1_email = models.CharField(max_length=255, blank=True)
    truck1_phone = models.CharField(max_length=255, blank=True)
    truck2_name = models.CharField(max_length=255, blank=True)
    truck2_email = models.CharField(max_length=255, blank=True)
    truck2_phone = models.CharField(max_length=255, blank=True)
    truck3_name = models.CharField(max_length=255, blank=True)
    truck3_email = models.CharField(max_length=255, blank=True)
    truck3_phone = models.CharField(max_length=255, blank=True)
    car1_name = models.CharField(max_length=255, blank=True)
    car1_email = models.CharField(max_length=255, blank=True)
    car1_phone = models.CharField(max_length=255, blank=True)
    car2_name = models.CharField(max_length=255, blank=True)
    car2_email = models.CharField(max_length=255, blank=True)
    car2_phone = models.CharField(max_length=255, blank=True)
    car3_name = models.CharField(max_length=255, blank=True)
    car3_email = models.CharField(max_length=255, blank=True)
    car3_phone = models.CharField(max_length=255, blank=True)
    catering_co_1_name = models.CharField(max_length=255, blank=True)
    catering_co_1_email = models.CharField(max_length=255, blank=True)
    catering_co_1_phone = models.CharField(max_length=255, blank=True)
    catering_co_2_name = models.CharField(max_length=255, blank=True)
    catering_co_2_email = models.CharField(max_length=255, blank=True)
    catering_co_2_phone = models.CharField(max_length=255, blank=True)
    catering_co_3_name = models.CharField(max_length=255, blank=True)
    catering_co_3_email = models.CharField(max_length=255, blank=True)
    catering_co_3_phone = models.CharField(max_length=255, blank=True)
    craft_service_name = models.CharField(max_length=255, blank=True)
    craft_service_email = models.CharField(max_length=255, blank=True)
    craft_service_phone = models.CharField(max_length=255, blank=True)
    crafty_ass_name = models.CharField(max_length=255, blank=True)
    crafty_ass_email = models.CharField(max_length=255, blank=True)
    crafty_ass_phone = models.CharField(max_length=255, blank=True)
    add_pos_1_job = models.CharField(max_length=255, blank=True)
    add_pos_1_name = models.CharField(max_length=255, blank=True)
    add_pos_1_email = models.CharField(max_length=255, blank=True)
    add_pos_1_phone = models.CharField(max_length=255, blank=True)
    add_pos_2_job = models.CharField(max_length=255, blank=True)
    add_pos_2_name = models.CharField(max_length=255, blank=True)
    add_pos_2_email = models.CharField(max_length=255, blank=True)
    add_pos_2_phone = models.CharField(max_length=255, blank=True)
    add_pos_3_job = models.CharField(max_length=255, blank=True)
    add_pos_3_name = models.CharField(max_length=255, blank=True)
    add_pos_3_email = models.CharField(max_length=255, blank=True)
    add_pos_3_phone = models.CharField(max_length=255, blank=True)
    add_pos_4_job = models.CharField(max_length=255, blank=True)
    add_pos_4_name = models.CharField(max_length=255, blank=True)
    add_pos_4_email = models.CharField(max_length=255, blank=True)
    add_pos_4_phone = models.CharField(max_length=255, blank=True)
    add_pos_5_job = models.CharField(max_length=255, blank=True)
    add_pos_5_name = models.CharField(max_length=255, blank=True)
    add_pos_5_email = models.CharField(max_length=255, blank=True)
    add_pos_5_phone = models.CharField(max_length=255, blank=True)
    add_pos_6_job = models.CharField(max_length=255, blank=True)
    add_pos_6_name = models.CharField(max_length=255, blank=True)
    add_pos_6_email = models.CharField(max_length=255, blank=True)
    add_pos_6_phone = models.CharField(max_length=255, blank=True)
    add_pos_7_job = models.CharField(max_length=255, blank=True)
    add_pos_7_name = models.CharField(max_length=255, blank=True)
    add_pos_7_email = models.CharField(max_length=255, blank=True)
    add_pos_7_phone = models.CharField(max_length=255, blank=True)
    add_pos_8_job = models.CharField(max_length=255, blank=True)
    add_pos_8_name = models.CharField(max_length=255, blank=True)
    add_pos_8_email = models.CharField(max_length=255, blank=True)
    add_pos_8_phone = models.CharField(max_length=255, blank=True)
    add_pos_9_job = models.CharField(max_length=255, blank=True)
    add_pos_9_name = models.CharField(max_length=255, blank=True)
    add_pos_9_email = models.CharField(max_length=255, blank=True)
    add_pos_9_phone = models.CharField(max_length=255, blank=True)
    add_pos_10_job = models.CharField(max_length=255, blank=True)
    add_pos_10_name = models.CharField(max_length=255, blank=True)
    add_pos_10_email = models.CharField(max_length=255, blank=True)
    add_pos_10_phone = models.CharField(max_length=255, blank=True)
    all_other_add_positions = models.TextField(blank=True)

    class Meta:
        ordering = ['production_name']

    def __str__(self):
        return f'{self.production_name}'


class Callsheetnew(models.Model):
    """
    Callsheetnew Model
    """
    # INFO
    day_id = models.ForeignKey(Day, on_delete=models.CASCADE)
    day = models.TextField(blank=True)
    date = models.TextField(blank=True, default="")
    unit_call = models.CharField(max_length=255, blank=True)
    talent_call = models.CharField(max_length=255, blank=True)
    shoot_call = models.CharField(max_length=255, blank=True)
    breakfast = models.CharField(max_length=255, blank=True)
    lunch = models.CharField(max_length=255, blank=True)
    wrap = models.CharField(max_length=255, blank=True)
    basecamp_name = models.TextField(blank=True)
    basecamp_address = models.TextField(blank=True)
    basecamp_parking_n_notes = models.TextField(blank=True)
    location_1_name = models.TextField(blank=True)
    location_2_name = models.TextField(blank=True)
    location_3_name = models.TextField(blank=True)
    location_4_name = models.TextField(blank=True)
    location_5_name = models.TextField(blank=True)
    location_1_address = models.TextField(blank=True)
    location_2_address = models.TextField(blank=True)
    location_3_address = models.TextField(blank=True)
    location_4_address = models.TextField(blank=True)
    location_5_address = models.TextField(blank=True)
    location_1_parking_n_notes = models.TextField(blank=True)
    location_2_parking_n_notes = models.TextField(blank=True)
    location_3_parking_n_notes = models.TextField(blank=True)
    location_4_parking_n_notes = models.TextField(blank=True)
    location_5_parking_n_notes = models.TextField(blank=True)
    nearest_hospital = models.TextField(blank=True)
    hospital_address_line_1 = models.TextField(blank=True)
    hospital_address_line_2 = models.TextField(blank=True)
    hospital_address_line_3 = models.TextField(blank=True)
    hospital_address_line_4 = models.TextField(blank=True)
    weather_location = models.CharField(max_length=255, blank=True)
    important_info = models.TextField(blank=True)
    transport_info = models.TextField(blank=True)
    department_info = models.TextField(blank=True)
    walkie_channel_production = models.CharField(max_length=255, blank=True)
    walkie_channel_open = models.CharField(max_length=255, blank=True)
    walkie_channel_transportation = models.CharField(
        max_length=255, blank=True)
    walkie_channel_art_dept = models.CharField(max_length=255, blank=True)
    walkie_channel_rollover = models.CharField(max_length=255, blank=True)
    walkie_channel_camera = models.CharField(max_length=255, blank=True)
    walkie_channel_electric = models.CharField(max_length=255, blank=True)
    walkie_channel_grip = models.CharField(max_length=255, blank=True)
    # CALLS
    # production
    director_calltime = models.CharField(max_length=255, blank=True)
    producer_calltime = models.CharField(max_length=255, blank=True)
    pro_coordinator_calltime = models.CharField(max_length=255, blank=True)
    travel_coordinator_calltime = models.CharField(max_length=255, blank=True)
    upm_calltime = models.CharField(max_length=255, blank=True)
    production_pa_calltime = models.CharField(max_length=255, blank=True)
    script_supervisor_calltime = models.CharField(max_length=255, blank=True)
    legal_calltime = models.CharField(max_length=255, blank=True)
    set_medic_calltime = models.CharField(max_length=255, blank=True)
    oth_production_pos_1_calltime = models.CharField(
        max_length=255, blank=True)
    oth_production_pos_2_calltime = models.CharField(
        max_length=255, blank=True)
    oth_production_pos_3_calltime = models.CharField(
        max_length=255, blank=True)
    oth_production_pos_4_calltime = models.CharField(
        max_length=255, blank=True)
    oth_production_pos_5_calltime = models.CharField(
        max_length=255, blank=True)
    # art
    production_designer_calltime = models.CharField(max_length=255, blank=True)
    art_director_calltime = models.CharField(max_length=255, blank=True)
    art_assistant_calltime = models.CharField(max_length=255, blank=True)
    set_decorator_calltime = models.CharField(max_length=255, blank=True)
    set_dresser_calltime = models.CharField(max_length=255, blank=True)
    lead_man_calltime = models.CharField(max_length=255, blank=True)
    dresser_calltime = models.CharField(max_length=255, blank=True)
    prop_master_calltime = models.CharField(max_length=255, blank=True)
    ass_prop_master_calltime = models.CharField(max_length=255, blank=True)
    prop_buyer_calltime = models.CharField(max_length=255, blank=True)
    armorer_calltime = models.CharField(max_length=255, blank=True)
    # camera
    dop_calltime = models.CharField(max_length=255, blank=True)
    camera_operator_calltime = models.CharField(max_length=255, blank=True)
    camera_ass_1_calltime = models.CharField(max_length=255, blank=True)
    camera_ass_2_calltime = models.CharField(max_length=255, blank=True)
    dit_calltime = models.CharField(max_length=255, blank=True)
    steadicam_calltime = models.CharField(max_length=255, blank=True)
    camera_pa_calltime = models.CharField(max_length=255, blank=True)
    oth_camera_pos_1_calltime = models.CharField(max_length=255, blank=True)
    oth_camera_pos_2_calltime = models.CharField(max_length=255, blank=True)
    oth_camera_pos_3_calltime = models.CharField(max_length=255, blank=True)
    # casting/AD
    casting_director_calltime = models.CharField(max_length=255, blank=True)
    extras_casting_calltime = models.CharField(max_length=255, blank=True)
    ad_1_calltime = models.CharField(max_length=255, blank=True)
    ad_2_calltime = models.CharField(max_length=255, blank=True)
    ad_3_calltime = models.CharField(max_length=255, blank=True)
    ad_4_calltime = models.CharField(max_length=255, blank=True)
    ad_5_calltime = models.CharField(max_length=255, blank=True)
    pro_assistant_1_calltime = models.CharField(max_length=255, blank=True)
    pro_assistant_2_calltime = models.CharField(max_length=255, blank=True)
    pro_assistant_3_calltime = models.CharField(max_length=255, blank=True)
    pro_assistant_4_calltime = models.CharField(max_length=255, blank=True)
    pro_assistant_5_calltime = models.CharField(max_length=255, blank=True)
    # eleGrip
    gaffer_calltime = models.CharField(max_length=255, blank=True)
    best_boy_electric_calltime = models.CharField(max_length=255, blank=True)
    electric_3_calltime = models.CharField(max_length=255, blank=True)
    electric_4_calltime = models.CharField(max_length=255, blank=True)
    keygrip_calltime = models.CharField(max_length=255, blank=True)
    best_boy_grip_calltime = models.CharField(max_length=255, blank=True)
    dolly_grip_calltime = models.CharField(max_length=255, blank=True)
    swing_ge1_calltime = models.CharField(max_length=255, blank=True)
    swing_ge2_calltime = models.CharField(max_length=255, blank=True)
    swing_ge3_calltime = models.CharField(max_length=255, blank=True)
    swing_ge4_calltime = models.CharField(max_length=255, blank=True)
    swing_ge5_calltime = models.CharField(max_length=255, blank=True)
    # locations
    location_mngr_calltime = models.CharField(max_length=255, blank=True)
    location_security_calltime = models.CharField(max_length=255, blank=True)
    location_ass_1_calltime = models.CharField(max_length=255, blank=True)
    location_ass_2_calltime = models.CharField(max_length=255, blank=True)
    location_ass_3_calltime = models.CharField(max_length=255, blank=True)
    location_ass_4_calltime = models.CharField(max_length=255, blank=True)
    # makeup
    key_hairmakeup_calltime = models.CharField(max_length=255, blank=True)
    key_hairstylist_calltime = models.CharField(max_length=255, blank=True)
    sfx_makeup_calltime = models.CharField(max_length=255, blank=True)
    sfx_makeup_assistant_calltime = models.CharField(
        max_length=255, blank=True)
    makeup_artist_1_calltime = models.CharField(max_length=255, blank=True)
    makeup_artist_2_calltime = models.CharField(max_length=255, blank=True)
    makeup_artist_3_calltime = models.CharField(max_length=255, blank=True)
    makeup_artist_4_calltime = models.CharField(max_length=255, blank=True)
    makeup_artist_5_calltime = models.CharField(max_length=255, blank=True)
    # post/add-pos
    editor_calltime = models.CharField(max_length=255, blank=True)
    fx_calltime = models.CharField(max_length=255, blank=True)
    add_pos_1_calltime = models.CharField(max_length=255, blank=True)
    add_pos_2_calltime = models.CharField(max_length=255, blank=True)
    add_pos_3_calltime = models.CharField(max_length=255, blank=True)
    add_pos_4_calltime = models.CharField(max_length=255, blank=True)
    add_pos_5_calltime = models.CharField(max_length=255, blank=True)
    add_pos_6_calltime = models.CharField(max_length=255, blank=True)
    add_pos_7_calltime = models.CharField(max_length=255, blank=True)
    add_pos_8_calltime = models.CharField(max_length=255, blank=True)
    add_pos_9_calltime = models.CharField(max_length=255, blank=True)
    add_pos_10_calltime = models.CharField(max_length=255, blank=True)
    all_other_add_positions_calltimes = models.TextField(blank=True)
    # script/cater
    writer_calltime = models.CharField(max_length=255, blank=True)
    catering_co_1_calltime = models.CharField(max_length=255, blank=True)
    catering_co_2_calltime = models.CharField(max_length=255, blank=True)
    catering_co_3_calltime = models.CharField(max_length=255, blank=True)
    craft_service_calltime = models.CharField(max_length=255, blank=True)
    crafty_ass_calltime = models.CharField(max_length=255, blank=True)
    # sound/transport
    sound_mixer_calltime = models.CharField(max_length=255, blank=True)
    boom_operator_calltime = models.CharField(max_length=255, blank=True)
    sound_assistant_1_calltime = models.CharField(max_length=255, blank=True)
    sound_assistant_2_calltime = models.CharField(max_length=255, blank=True)
    transport_captain_calltime = models.CharField(max_length=255, blank=True)
    transport_manager_1_calltime = models.CharField(max_length=255, blank=True)
    transport_manager_2_calltime = models.CharField(max_length=255, blank=True)
    head_driver_calltime = models.CharField(max_length=255, blank=True)
    car1_calltime = models.CharField(max_length=255, blank=True)
    car2_calltime = models.CharField(max_length=255, blank=True)
    car3_calltime = models.CharField(max_length=255, blank=True)
    truck1_calltime = models.CharField(max_length=255, blank=True)
    truck2_calltime = models.CharField(max_length=255, blank=True)
    truck3_calltime = models.CharField(max_length=255, blank=True)
    # stunts
    stunt_coordinator_calltime = models.CharField(max_length=255, blank=True)
    stunts_1_calltime = models.CharField(max_length=255, blank=True)
    stunts_2_calltime = models.CharField(max_length=255, blank=True)
    stunts_3_calltime = models.CharField(max_length=255, blank=True)
    stunts_4_calltime = models.CharField(max_length=255, blank=True)
    stunts_5_calltime = models.CharField(max_length=255, blank=True)
    # wardrobe
    costume_designer_calltime = models.CharField(max_length=255, blank=True)
    ass_costume_designer_calltime = models.CharField(
        max_length=255, blank=True)
    wardrobe_assistant_1_calltime = models.CharField(
        max_length=255, blank=True)
    wardrobe_assistant_2_calltime = models.CharField(
        max_length=255, blank=True)
    wardrobe_assistant_3_calltime = models.CharField(
        max_length=255, blank=True)
    wardrobe_assistant_4_calltime = models.CharField(
        max_length=255, blank=True)
    wardrobe_assistant_5_calltime = models.CharField(
        max_length=255, blank=True)

    class Meta:
        ordering = ['day']

    def __str__(self):
        return f'{self.day}'


class Castcallnew(models.Model):
    """
    Castcallnew Model
    """

    day_id = models.ForeignKey(Day, on_delete=models.CASCADE)
    shoot_day = models.CharField(max_length=255, blank=True)
    shoot_date = models.CharField(max_length=255, blank=True)
    cast_number = models.IntegerField(blank=False)
    username = models.CharField(max_length=255, blank=True)
    role = models.CharField(max_length=255, blank=True)
    artist = models.CharField(max_length=255, blank=True)
    contact = models.CharField(max_length=255, blank=True)
    email = models.CharField(max_length=255, blank=True)
    swf = models.CharField(max_length=255, blank=True)
    pickup = models.CharField(max_length=255, blank=True)
    call = models.TextField(blank=True)
    hmw = models.TextField(blank=True)
    on_set = models.TextField(blank=True)
    inst = models.TextField(blank=True)

    class Meta:
        ordering = ['cast_number']

    def __str__(self):
        return f'{self.role}'


class Backgroundcallnew(models.Model):
    """
    Backgroundcallnew Model
    """

    day_id = models.ForeignKey(Day, on_delete=models.CASCADE)
    shoot_day = models.CharField(max_length=255, blank=True)
    shoot_date = models.CharField(max_length=255, blank=True)
    qty = models.CharField(max_length=255, blank=True)
    type = models.CharField(max_length=255, blank=True)
    call = models.CharField(max_length=255, blank=True)
    scenes = models.CharField(max_length=255, blank=True)
    set = models.CharField(max_length=255, blank=True)
    costumes = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ['call']

    def __str__(self):
        return f'{self.type}'
