# Generated by Django 3.2.9 on 2023-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departments',
            field=models.CharField(choices=[('camera', 'Camera'), ('script', 'Script'), ('art', 'Art'), ('make-up', 'Hair/Make-up'), ('wardrobe', 'Wardrobe'), ('location', 'Location'), ('sound', 'Sound'), ('casting', 'Casting'), ('post', 'Post/VSF'), ('production', 'Production'), ('stunts', 'Stunts'), ('electric', 'Electric/Grip'), ('latest', 'Latest')], default='camera', max_length=32),
        ),
    ]
