# Generated by Django 3.2.9 on 2022-01-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('filming_address_primary', models.TextField(blank=True)),
                ('filming_address2', models.TextField(blank=True)),
                ('filming_address3', models.TextField(blank=True)),
                ('image1_description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='images/')),
                ('image2_description', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('image3_description', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, upload_to='images/')),
                ('image4_description', models.TextField(blank=True)),
                ('image4', models.ImageField(blank=True, upload_to='images/')),
                ('image5_description', models.TextField(blank=True)),
                ('image5', models.ImageField(blank=True, upload_to='images/')),
                ('image6_description', models.TextField(blank=True)),
                ('image6', models.ImageField(blank=True, upload_to='images/')),
                ('image7_description', models.TextField(blank=True)),
                ('image7', models.ImageField(blank=True, upload_to='images/')),
                ('image8_description', models.TextField(blank=True)),
                ('image8', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
