# Generated by Django 3.2.9 on 2022-03-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0003_auto_20220325_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetnew',
            name='basecamp_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='location_1_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='location_2_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='location_3_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='location_4_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='location_5_name',
            field=models.TextField(blank=True),
        ),
    ]
