# Generated by Django 3.2.9 on 2022-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0004_auto_20220330_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetnew',
            name='all_other_add_positions_calltimes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='hospital_address_line_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='hospital_address_line_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='hospital_address_line_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='hospital_address_line_4',
            field=models.TextField(blank=True),
        ),
    ]
