# Generated by Django 3.2.9 on 2022-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0005_auto_20220405_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetnew',
            name='production_designer_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
