# Generated by Django 3.2.9 on 2022-05-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0006_callsheetnew_production_designer_calltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetnew',
            name='armorer_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
