# Generated by Django 3.2.9 on 2022-05-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0007_callsheetnew_armorer_calltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='castcallnew',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
