# Generated by Django 3.2.9 on 2022-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0008_castcallnew_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewinfonew',
            name='production_pa_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='upm_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='upm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='upm_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
