# Generated by Django 3.2.9 on 2022-11-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0009_auto_20221112_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castcallnew',
            options={'ordering': ['call']},
        ),
    ]
