# Generated by Django 3.2.9 on 2022-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0010_alter_castcallnew_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castcallnew',
            options={'ordering': ['cast_number']},
        ),
        migrations.AlterField(
            model_name='castcallnew',
            name='cast_number',
            field=models.IntegerField(),
        ),
    ]
