# Generated by Django 3.2.9 on 2023-05-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0012_castcallnew_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_10_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_10_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_10_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_10_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_1_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_1_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_1_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_1_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_2_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_2_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_2_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_2_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_3_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_3_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_3_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_3_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_4_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_4_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_4_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_4_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_5_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_5_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_5_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_5_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_6_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_6_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_6_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_6_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_7_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_7_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_7_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_7_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_8_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_8_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_8_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_8_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_9_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_9_job',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_9_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewinfonew',
            name='xtra_camera_pos_9_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
