# Generated by Django 3.2.9 on 2023-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0013_auto_20230520_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheetnew',
            name='oth_camera_pos_4_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='oth_camera_pos_5_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_10_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_1_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_2_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_3_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_4_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_5_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_6_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_7_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_8_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callsheetnew',
            name='xtra_camera_pos_9_calltime',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
