# Generated by Django 3.2.9 on 2023-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheetsnew', '0014_auto_20230521_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewinfonew',
            name='freeze',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
