# Generated by Django 3.2.9 on 2022-07-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_changes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('script', models.FileField(blank=True, default='', upload_to='images/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
