# Generated by Django 3.2.9 on 2022-01-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenes', '0010_scene_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shotlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.CharField(blank=True, max_length=255)),
                ('shot_number', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('angle', models.TextField(blank=True)),
                ('movement', models.CharField(blank=True, max_length=255)),
                ('fx', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('focus_pulls', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True, max_length=255)),
                ('lighting', models.TextField(blank=True)),
                ('camera', models.TextField(blank=True)),
                ('lens', models.TextField(blank=True)),
                ('screen_time', models.TextField(blank=True)),
                ('script_length', models.TextField(blank=True)),
                ('script_ref', models.TextField(blank=True)),
                ('storyboard_refs', models.TextField(blank=True)),
                ('scene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.scene')),
            ],
            options={
                'ordering': ['scene_number', 'shot_number'],
            },
        ),
    ]
