# Generated by Django 3.2.9 on 2022-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotlist',
            name='audio',
            field=models.TextField(blank=True),
        ),
    ]
