# Generated by Django 3.2.9 on 2024-11-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotlists', '0005_alter_shotlist_shot_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shotlist',
            old_name='screen_time',
            new_name='actors',
        ),
        migrations.RenameField(
            model_name='shotlist',
            old_name='script_length',
            new_name='location',
        ),
        migrations.AddField(
            model_name='shotlist',
            name='frame_rate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shotlist',
            name='framing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shotlist',
            name='int_ext',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shotlist',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
