# Generated by Django 3.2.9 on 2024-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotlists', '0007_auto_20241124_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotlist',
            name='int_ext',
            field=models.CharField(blank=True, choices=[('EXT.', 'EXT'), ('INT.', 'INT')], max_length=32),
        ),
    ]
